services:
  app:
    build:
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_pass
    depends_on:
      - mysql
      
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - ../database:/var/lib/mysql
    entrypoint: >
      sh -c "mkdir -p ../database && exec docker-entrypoint.sh mysqld"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "8080:80"
    depends_on:
      - mysql